# Generated by urdf.parser.codegen. Do not edit manually.
from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any, Literal, overload

from urdf.kinematics.kinematic_chain import JointId, LinkId, Skeleton

from .models.g1_23dof import (
    UNITREE_G1_23DOF,
    UnitreeG1_23DOFJointId,
    UnitreeG1_23DOFLinkId,
)
from .models.g1_29dof import (
    UNITREE_G1_29DOF,
    UnitreeG1_29DOFJointId,
    UnitreeG1_29DOFLinkId,
)
from .models.h1 import (
    UNITREE_H1,
    UnitreeH1JointId,
    UnitreeH1LinkId,
)
from .models.h1_with_hand import (
    UNITREE_H1_WITH_HAND,
    UnitreeH1WithHandJointId,
    UnitreeH1WithHandLinkId,
)
from .models.t1_locomotion import (
    BOOSTER_T1_LOCOMOTION,
    BoosterT1LocomotionJointId,
    BoosterT1LocomotionLinkId,
)
from .models.t1_serial import (
    BOOSTER_T1_SERIAL,
    BoosterT1SerialJointId,
    BoosterT1SerialLinkId,
)
from .models.x1 import (
    AGIBOT_X1,
    AgiBotX1JointId,
    AgiBotX1LinkId,
)


class RobotId(StrEnum):
    """Identifiers for built-in robot definitions."""

    UNITREE_G1_23DOF = "unitree_g1_23dof"
    """The Unitree G1 23-DOF humanoid robot."""

    UNITREE_G1_29DOF = "unitree_g1_29dof"
    """The Unitree G1 29-DOF humanoid robot."""

    UNITREE_H1 = "unitree_h1"
    """The Unitree H1 humanoid robot."""

    UNITREE_H1_WITH_HAND = "unitree_h1_with_hand"
    """The Unitree H1 humanoid robot with a hand."""

    BOOSTER_T1_LOCOMOTION = "booster_t1_locomotion"
    """The Booster T1 humanoid robot with head, arms, and waist fixed (12 actuated leg DOFs)."""

    BOOSTER_T1_SERIAL = "booster_t1_serial"
    """The Booster T1 humanoid robot with all 23 DOFs actuated."""

    AGIBOT_X1 = "agibot_x1"
    """The AgiBot X1 humanoid robot."""


@dataclass(frozen=True, kw_only=True)
class Robot[LinkIdT: LinkId, JointIdT: JointId]:
    """A robot model with kinematics and metadata."""

    id: str
    """The identifier of the robot."""

    name: str
    """The human-readable name of the robot."""

    skeleton: Skeleton[LinkIdT, JointIdT]
    """The kinematic chain of the robot."""


type AnyRobot = Robot[Any, Any]
"""A robot whose concrete link and joint identifier types are erased."""

type UnitreeG1_23DOFRobot = Robot[UnitreeG1_23DOFLinkId, UnitreeG1_23DOFJointId]
"""The robot type for the Unitree G1 23-DOF robot."""

type UnitreeG1_23DOFSkeleton = Skeleton[UnitreeG1_23DOFLinkId, UnitreeG1_23DOFJointId]
"""The skeleton type for the Unitree G1 23-DOF robot."""

type UnitreeG1_29DOFRobot = Robot[UnitreeG1_29DOFLinkId, UnitreeG1_29DOFJointId]
"""The robot type for the Unitree G1 29-DOF robot."""

type UnitreeG1_29DOFSkeleton = Skeleton[UnitreeG1_29DOFLinkId, UnitreeG1_29DOFJointId]
"""The skeleton type for the Unitree G1 29-DOF robot."""

type UnitreeH1Robot = Robot[UnitreeH1LinkId, UnitreeH1JointId]
"""The robot type for the Unitree H1 robot."""

type UnitreeH1Skeleton = Skeleton[UnitreeH1LinkId, UnitreeH1JointId]
"""The skeleton type for the Unitree H1 robot."""

type UnitreeH1WithHandRobot = Robot[UnitreeH1WithHandLinkId, UnitreeH1WithHandJointId]
"""The robot type for the Unitree H1 with Hand robot."""

type UnitreeH1WithHandSkeleton = Skeleton[
    UnitreeH1WithHandLinkId, UnitreeH1WithHandJointId
]
"""The skeleton type for the Unitree H1 with Hand robot."""

type BoosterT1LocomotionRobot = Robot[
    BoosterT1LocomotionLinkId, BoosterT1LocomotionJointId
]
"""The robot type for the Booster T1 Locomotion robot."""

type BoosterT1LocomotionSkeleton = Skeleton[
    BoosterT1LocomotionLinkId, BoosterT1LocomotionJointId
]
"""The skeleton type for the Booster T1 Locomotion robot."""

type BoosterT1SerialRobot = Robot[BoosterT1SerialLinkId, BoosterT1SerialJointId]
"""The robot type for the Booster T1 Serial robot."""

type BoosterT1SerialSkeleton = Skeleton[BoosterT1SerialLinkId, BoosterT1SerialJointId]
"""The skeleton type for the Booster T1 Serial robot."""

type AgiBotX1Robot = Robot[AgiBotX1LinkId, AgiBotX1JointId]
"""The robot type for the AgiBot X1 robot."""

type AgiBotX1Skeleton = Skeleton[AgiBotX1LinkId, AgiBotX1JointId]
"""The skeleton type for the AgiBot X1 robot."""

type AnySkeleton = Skeleton[Any, Any]
"""A skeleton whose concrete link and joint identifier types are erased."""

UNITREE_G1_23DOF_ROBOT = Robot[UnitreeG1_23DOFLinkId, UnitreeG1_23DOFJointId](
    id=RobotId.UNITREE_G1_23DOF,
    name="Unitree G1 23-DOF",
    skeleton=UNITREE_G1_23DOF,
)
"""The robot model for the Unitree G1 23-DOF robot."""

UNITREE_G1_29DOF_ROBOT = Robot[UnitreeG1_29DOFLinkId, UnitreeG1_29DOFJointId](
    id=RobotId.UNITREE_G1_29DOF,
    name="Unitree G1 29-DOF",
    skeleton=UNITREE_G1_29DOF,
)
"""The robot model for the Unitree G1 29-DOF robot."""

UNITREE_H1_ROBOT = Robot[UnitreeH1LinkId, UnitreeH1JointId](
    id=RobotId.UNITREE_H1,
    name="Unitree H1",
    skeleton=UNITREE_H1,
)
"""The robot model for the Unitree H1 robot."""

UNITREE_H1_WITH_HAND_ROBOT = Robot[UnitreeH1WithHandLinkId, UnitreeH1WithHandJointId](
    id=RobotId.UNITREE_H1_WITH_HAND,
    name="Unitree H1 with Hand",
    skeleton=UNITREE_H1_WITH_HAND,
)
"""The robot model for the Unitree H1 with Hand robot."""

BOOSTER_T1_LOCOMOTION_ROBOT = Robot[
    BoosterT1LocomotionLinkId, BoosterT1LocomotionJointId
](
    id=RobotId.BOOSTER_T1_LOCOMOTION,
    name="Booster T1 Locomotion",
    skeleton=BOOSTER_T1_LOCOMOTION,
)
"""The robot model for the Booster T1 Locomotion robot."""

BOOSTER_T1_SERIAL_ROBOT = Robot[BoosterT1SerialLinkId, BoosterT1SerialJointId](
    id=RobotId.BOOSTER_T1_SERIAL,
    name="Booster T1 Serial",
    skeleton=BOOSTER_T1_SERIAL,
)
"""The robot model for the Booster T1 Serial robot."""

AGIBOT_X1_ROBOT = Robot[AgiBotX1LinkId, AgiBotX1JointId](
    id=RobotId.AGIBOT_X1,
    name="AgiBot X1",
    skeleton=AGIBOT_X1,
)
"""The robot model for the AgiBot X1 robot."""

_BUILT_IN_ROBOT_IDS = frozenset(str(robot_id) for robot_id in RobotId)
_ROBOTS: dict[str, AnyRobot] = {
    str(RobotId.UNITREE_G1_23DOF): UNITREE_G1_23DOF_ROBOT,
    str(RobotId.UNITREE_G1_29DOF): UNITREE_G1_29DOF_ROBOT,
    str(RobotId.UNITREE_H1): UNITREE_H1_ROBOT,
    str(RobotId.UNITREE_H1_WITH_HAND): UNITREE_H1_WITH_HAND_ROBOT,
    str(RobotId.BOOSTER_T1_LOCOMOTION): BOOSTER_T1_LOCOMOTION_ROBOT,
    str(RobotId.BOOSTER_T1_SERIAL): BOOSTER_T1_SERIAL_ROBOT,
    str(RobotId.AGIBOT_X1): AGIBOT_X1_ROBOT,
}


@overload
def get_robot(robot_id: Literal[RobotId.UNITREE_G1_23DOF]) -> UnitreeG1_23DOFRobot:
    """Return the robot model for the Unitree G1 23-DOF robot."""
    ...


@overload
def get_robot(robot_id: Literal[RobotId.UNITREE_G1_29DOF]) -> UnitreeG1_29DOFRobot:
    """Return the robot model for the Unitree G1 29-DOF robot."""
    ...


@overload
def get_robot(robot_id: Literal[RobotId.UNITREE_H1]) -> UnitreeH1Robot:
    """Return the robot model for the Unitree H1 robot."""
    ...


@overload
def get_robot(
    robot_id: Literal[RobotId.UNITREE_H1_WITH_HAND],
) -> UnitreeH1WithHandRobot:
    """Return the robot model for the Unitree H1 with Hand robot."""
    ...


@overload
def get_robot(
    robot_id: Literal[RobotId.BOOSTER_T1_LOCOMOTION],
) -> BoosterT1LocomotionRobot:
    """Return the robot model for the Booster T1 Locomotion robot."""
    ...


@overload
def get_robot(robot_id: Literal[RobotId.BOOSTER_T1_SERIAL]) -> BoosterT1SerialRobot:
    """Return the robot model for the Booster T1 Serial robot."""
    ...


@overload
def get_robot(robot_id: Literal[RobotId.AGIBOT_X1]) -> AgiBotX1Robot:
    """Return the robot model for the AgiBot X1 robot."""
    ...


@overload
def get_robot(robot_id: str) -> AnyRobot:
    """Return the robot model for the given robot identifier."""
    ...


def get_robot(robot_id: str) -> AnyRobot:
    """Return the robot model for the given robot identifier."""
    try:
        return _ROBOTS[str(robot_id)]
    except KeyError as exc:
        raise KeyError(f"No robot registered for {robot_id!r}.") from exc


@overload
def get_skeleton(
    robot_id: Literal[RobotId.UNITREE_G1_23DOF],
) -> UnitreeG1_23DOFSkeleton:
    """Return the skeleton for the Unitree G1 23-DOF robot."""
    ...


@overload
def get_skeleton(
    robot_id: Literal[RobotId.UNITREE_G1_29DOF],
) -> UnitreeG1_29DOFSkeleton:
    """Return the skeleton for the Unitree G1 29-DOF robot."""
    ...


@overload
def get_skeleton(
    robot_id: Literal[RobotId.UNITREE_H1],
) -> UnitreeH1Skeleton:
    """Return the skeleton for the Unitree H1 robot."""
    ...


@overload
def get_skeleton(
    robot_id: Literal[RobotId.UNITREE_H1_WITH_HAND],
) -> UnitreeH1WithHandSkeleton:
    """Return the skeleton for the Unitree H1 with Hand robot."""
    ...


@overload
def get_skeleton(
    robot_id: Literal[RobotId.BOOSTER_T1_LOCOMOTION],
) -> BoosterT1LocomotionSkeleton:
    """Return the skeleton for the Booster T1 Locomotion robot."""
    ...


@overload
def get_skeleton(
    robot_id: Literal[RobotId.BOOSTER_T1_SERIAL],
) -> BoosterT1SerialSkeleton:
    """Return the skeleton for the Booster T1 Serial robot."""
    ...


@overload
def get_skeleton(
    robot_id: Literal[RobotId.AGIBOT_X1],
) -> AgiBotX1Skeleton:
    """Return the skeleton for the AgiBot X1 robot."""
    ...


@overload
def get_skeleton(robot_id: str) -> AnySkeleton:
    """Return the skeleton for the given robot identifier."""
    ...


def get_skeleton(robot_id: str) -> AnySkeleton:
    """Return the skeleton for the given robot identifier."""
    return get_robot(robot_id).skeleton


def register_robot(robot: AnyRobot, *, replace: bool = False) -> None:
    """Register a robot definition for runtime lookup."""
    robot_id = str(robot.id)
    if not robot_id:
        raise ValueError("Robot IDs cannot be empty.")
    if robot_id in _ROBOTS and not replace:
        raise ValueError(f"A robot is already registered for {robot_id!r}.")
    _ROBOTS[robot_id] = robot


def unregister_robot(robot_id: str, *, allow_builtin: bool = False) -> AnyRobot:
    """Remove and return a runtime robot definition."""
    normalized_id = str(robot_id)
    if normalized_id in _BUILT_IN_ROBOT_IDS and not allow_builtin:
        raise ValueError(f"Cannot unregister built-in robot {normalized_id!r}.")
    try:
        return _ROBOTS.pop(normalized_id)
    except KeyError as exc:
        raise KeyError(f"No robot registered for {robot_id!r}.") from exc


def registered_robot_ids() -> frozenset[str]:
    """Return the identifiers of all registered robots."""
    return frozenset(_ROBOTS)
