# Generated by urdf.parser.codegen. Do not edit manually.
"""Generated robot model definitions."""

from __future__ import annotations

from .g1_23dof import (
    UNITREE_G1_23DOF,
    UNITREE_G1_23DOF_ARTICULATION,
    UNITREE_G1_23DOF_LINKAGE,
    UnitreeG1_23DOFJoint,
    UnitreeG1_23DOFJointId,
    UnitreeG1_23DOFLink,
    UnitreeG1_23DOFLinkId,
)
from .g1_29dof import (
    UNITREE_G1_29DOF,
    UNITREE_G1_29DOF_ARTICULATION,
    UNITREE_G1_29DOF_LINKAGE,
    UnitreeG1_29DOFJoint,
    UnitreeG1_29DOFJointId,
    UnitreeG1_29DOFLink,
    UnitreeG1_29DOFLinkId,
)
from .h1 import (
    UNITREE_H1,
    UNITREE_H1_ARTICULATION,
    UNITREE_H1_LINKAGE,
    UnitreeH1Joint,
    UnitreeH1JointId,
    UnitreeH1Link,
    UnitreeH1LinkId,
)
from .h1_with_hand import (
    UNITREE_H1_WITH_HAND,
    UNITREE_H1_WITH_HAND_ARTICULATION,
    UNITREE_H1_WITH_HAND_LINKAGE,
    UnitreeH1WithHandJoint,
    UnitreeH1WithHandJointId,
    UnitreeH1WithHandLink,
    UnitreeH1WithHandLinkId,
)
from .t1_locomotion import (
    BOOSTER_T1_LOCOMOTION,
    BOOSTER_T1_LOCOMOTION_ARTICULATION,
    BOOSTER_T1_LOCOMOTION_LINKAGE,
    BoosterT1LocomotionJoint,
    BoosterT1LocomotionJointId,
    BoosterT1LocomotionLink,
    BoosterT1LocomotionLinkId,
)
from .t1_serial import (
    BOOSTER_T1_SERIAL,
    BOOSTER_T1_SERIAL_ARTICULATION,
    BOOSTER_T1_SERIAL_LINKAGE,
    BoosterT1SerialJoint,
    BoosterT1SerialJointId,
    BoosterT1SerialLink,
    BoosterT1SerialLinkId,
)
from .x1 import (
    AGIBOT_X1,
    AGIBOT_X1_ARTICULATION,
    AGIBOT_X1_LINKAGE,
    AgiBotX1Joint,
    AgiBotX1JointId,
    AgiBotX1Link,
    AgiBotX1LinkId,
)

__all__ = [
    # Unitree G1 23-DOF
    "UNITREE_G1_23DOF",
    "UNITREE_G1_23DOF_ARTICULATION",
    "UNITREE_G1_23DOF_LINKAGE",
    "UnitreeG1_23DOFJoint",
    "UnitreeG1_23DOFJointId",
    "UnitreeG1_23DOFLink",
    "UnitreeG1_23DOFLinkId",
    # Unitree G1 29-DOF
    "UNITREE_G1_29DOF",
    "UNITREE_G1_29DOF_ARTICULATION",
    "UNITREE_G1_29DOF_LINKAGE",
    "UnitreeG1_29DOFJoint",
    "UnitreeG1_29DOFJointId",
    "UnitreeG1_29DOFLink",
    "UnitreeG1_29DOFLinkId",
    # Unitree H1
    "UNITREE_H1",
    "UNITREE_H1_ARTICULATION",
    "UNITREE_H1_LINKAGE",
    "UnitreeH1Joint",
    "UnitreeH1JointId",
    "UnitreeH1Link",
    "UnitreeH1LinkId",
    # Unitree H1 with Hand
    "UNITREE_H1_WITH_HAND",
    "UNITREE_H1_WITH_HAND_ARTICULATION",
    "UNITREE_H1_WITH_HAND_LINKAGE",
    "UnitreeH1WithHandJoint",
    "UnitreeH1WithHandJointId",
    "UnitreeH1WithHandLink",
    "UnitreeH1WithHandLinkId",
    # Booster T1 Locomotion
    "BOOSTER_T1_LOCOMOTION",
    "BOOSTER_T1_LOCOMOTION_ARTICULATION",
    "BOOSTER_T1_LOCOMOTION_LINKAGE",
    "BoosterT1LocomotionJoint",
    "BoosterT1LocomotionJointId",
    "BoosterT1LocomotionLink",
    "BoosterT1LocomotionLinkId",
    # Booster T1 Serial
    "BOOSTER_T1_SERIAL",
    "BOOSTER_T1_SERIAL_ARTICULATION",
    "BOOSTER_T1_SERIAL_LINKAGE",
    "BoosterT1SerialJoint",
    "BoosterT1SerialJointId",
    "BoosterT1SerialLink",
    "BoosterT1SerialLinkId",
    # AgiBot X1
    "AGIBOT_X1",
    "AGIBOT_X1_ARTICULATION",
    "AGIBOT_X1_LINKAGE",
    "AgiBotX1Joint",
    "AgiBotX1JointId",
    "AgiBotX1Link",
    "AgiBotX1LinkId",
]
